version: "3.7"
services:
  app:
    build:
      args:
        user: scoreboard
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: scoreboard
    container_name: scoreboard-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - scoreboard

  redis:
      image: redis
      container_name: redis
      volumes:
          - ./docker/redis:/data
      ports:
          - 6379:6379
      networks:
          - scoreboard

  nginx:
    image: nginx:alpine
    container_name: scoreboard-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - scoreboard

networks:
  scoreboard:
    driver: bridge
