version: "3.7"
services:
  app:
    build:
      args:
        user: scoreboard
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: scoreboard
    container_name: scoreboard-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - scoreboard

  db:
    image: mysql:5.7
    container_name: scoreboard-db
    restart: unless-stopped
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - scoreboard

  nginx:
    image: nginx:alpine
    container_name: scoreboard-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - scoreboard

networks:
  scoreboard:
    driver: bridge
